version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=3000
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - API_KEY=${API_KEY}
